
simple_undirected.png simple_undirected.pdf: simple_undirected.gv
	neato -Tpng simple_undirected.gv > simple_undirected.png
	neato -Tpng simple_undirected.gv > simple_undirected.pdf

clean:
	rm -f *.png *.pdf
